In [2]:
from sklearn_pandas import DataFrameMapper, cross_val_score
import pandas as pd
import numpy as np
import sklearn.preprocessing, sklearn.decomposition, sklearn.linear_model, sklearn.pipeline, sklearn.metrics
from sklearn.feature_extraction.text import CountVectorizer
data = pd.DataFrame({'pet':      ['cat', 'dog', 'dog', 'fish', 'cat', 'dog', 'cat', 'fish'],
                      'children': [4., 6, 3, 3, 2, 3, 5, 4],
                     'salary':   [90, 24, 44, 27, 32, 59, 36, 27]})

In [3]:
mapper = DataFrameMapper([
     ('pet', sklearn.preprocessing.LabelBinarizer()),
     (['children'], sklearn.preprocessing.StandardScaler())])

In [3]:
np.round(mapper.fit_transform(data.copy()), 2)

array([[ 1.  ,  0.  ,  0.  ,  0.21],
       [ 0.  ,  1.  ,  0.  ,  1.88],
       [ 0.  ,  1.  ,  0.  , -0.63],
       [ 0.  ,  0.  ,  1.  , -0.63],
       [ 1.  ,  0.  ,  0.  , -1.46],
       [ 0.  ,  1.  ,  0.  , -0.63],
       [ 1.  ,  0.  ,  0.  ,  1.04],
       [ 0.  ,  0.  ,  1.  ,  0.21]])

In [4]:
sample = pd.DataFrame({'pet': ['cat'], 'children': [5.]})
np.round(mapper.transform(sample), 2)

array([[ 1.  ,  0.  ,  0.  ,  1.04]])

In [ ]:
mapper3 = DataFrameMapper([
(['age'], [sklearn.preprocessing.Imputer(),
...                sklearn.preprocessing.StandardScaler()])])
data_3 = pd.DataFrame({'age': [1, np.nan, 3]})
>>> mapper3.fit_transform(data_3)
array([[-1.22474487],
       [ 0.        ],
       [ 1.22474487]])

In [10]:
mapper4 = DataFrameMapper(
     [('pet', sklearn.preprocessing.LabelBinarizer()),('children', None)],
     default=sklearn.preprocessing.StandardScaler())
# np.round(mapper4.fit_transform(data.copy()), 1)

In [5]:
# mapper5 = DataFrameMapper([('children', None)], default=sklearn.preprocessing.StandardScaler())
mapper5 = DataFrameMapper([('children', None)])

In [6]:
data_3 = pd.DataFrame({'age': [1, np.nan, 3]})
mapper5.fit_transform(data)

array([[ 4.],
       [ 6.],
       [ 3.],
       [ 3.],
       [ 2.],
       [ 3.],
       [ 5.],
       [ 4.]])

In [7]:
data.head()

children   pet  salary
0       4.0   cat      90
1       6.0   dog      24
2       3.0   dog      44
3       3.0  fish      27
4       2.0   cat      32